all:
  hosts:
    node1:
      ansible_host: 192.168.60.2
      ip: 192.168.60.2
      access_ip: 192.168.60.2
    node2:
      ansible_host: 192.168.60.3
      ip: 192.168.60.3
      access_ip: 192.168.60.3
    node3:
      ansible_host: 192.168.60.4
      ip: 192.168.60.4
      access_ip: 192.168.60.4
    node4:
      ansible_host: 192.168.60.5
      ip: 192.168.60.5
      access_ip: 192.168.60.5
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
